networks:
  claimrequest_network:
    driver: bridge

services:
  claimrequest.db:
    container_name: claimrequest-db
    image: postgres:latest
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: Iloveyou3000!
      POSTGRES_DB: ClaimRequestDB
    ports:
      - "5432:5432"
    networks:
      - claimrequest_network
    volumes:
      - claimrequest.db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U db_user -d ClaimRequestDB" ]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    container_name: pgadmin_claimrequest
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - claimrequest.db
    networks:
      - claimrequest_network

volumes:
  claimrequest.db_data:
