name: FE Vercel CD
on:
  push:
    branches: ["main"]
    paths:
      - "claimrequest-fe-team1-dev/**"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: claimrequest-fe-team1-dev

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.6.5
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('claimrequest-fe-team1-dev/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --no-git-checks

      - name: Build the project
        run: pnpm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: claimrequest-fe-team1-dev/dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: claimrequest-fe-team1-dev/dist

      - name: Deploy to Production Repo
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          git config --global user.name "lcaohoanq"
          git config --global user.email "hoangclw@gmail.com"

          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_ed25519

          ssh-keyscan github.com >> ~/.ssh/known_hosts

          git clone git@github.com:lcaohoanq/crs.git production-repo
          rm -rf production-repo/dist
          cp -r claimrequest-fe-team1-dev/dist production-repo/

          cd production-repo
          git pull
          git add .
          if git diff --staged --quiet; then
            git commit --allow-empty -m "Trigger CD"
          else
            git commit -m "Deploy new build from ${{ github.ref_name }} branch"
          fi
          git push origin main
